[package]
name = "news-topic-search-rust-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
tera = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.11"
serde_json = "1.0"
actix-files = "0.6"
